### ISSUE TITLE
KAR injector support for Camel-K

### ISSUE THREAD

**Issue by tardieu** [IBM/kar#19]
To deploy Camel-K integrations using `kubectl` with need yaml such as:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: stock-source
spec:
  containers:
  - name: stock-source
    image: localhost:5000/kar/kar-examples-stock-source
    env:
    - name: KAFKA_BROKERS
      valueFrom:
        secretKeyRef:
          name: kar.ibm.com.runtime-config
          key: kafka_brokers
```
See https://github.com/IBM/kar/blob/main/examples/camel-k/deploy/stocks.yaml.

We could extend the mutating webhook to permit something like:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: stock-source
  annotations:
    kar.ibm.com/runtime: camel
spec:
  containers:
  - name: stock-source
    image: localhost:5000/kar/kar-examples-stock-source
```
